//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblGider
    {
        public int GİDERID { get; set; }
        public string GİDERAÇIKLAMA { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
        public Nullable<decimal> TUTAR { get; set; }
    }
}
