//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotlarım
    {
        public int ID { get; set; }
        public string BAŞLIK { get; set; }
        public string İÇERİK { get; set; }
        public Nullable<bool> OKUMA { get; set; }
        public Nullable<System.DateTime> TARİH { get; set; }
    }
}
