//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUrunKabul
    {
        public int İŞLEMID { get; set; }
        public Nullable<int> CARİ { get; set; }
        public Nullable<short> PERSONEL { get; set; }
        public Nullable<System.DateTime> GELİŞTARİHİ { get; set; }
        public Nullable<System.DateTime> ÇIKIŞTARİHİ { get; set; }
        public string ÜRÜNSERİNO { get; set; }
        public Nullable<bool> URUNDURUM { get; set; }
        public string URUNDURUMDETAY { get; set; }
    
        public virtual TblCari TblCari { get; set; }
        public virtual TblPersonel TblPersonel { get; set; }
    }
}
